In [ ]:
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
# 1 创建一个空白的图像
img = np.zeros((512,512,3), np.uint8)
# 2 绘制图形
cv.line(img,(0,0),(511,511),(255,0,0),5)
cv.rectangle(img,(384,0),(510,128),(0,255,0),3)
cv.circle(img,(447,63), 63, (0,0,255), -1)
font = cv.FONT_HERSHEY_SIMPLEX
#cv.putText(img,text,station, font, fontsize,color,thickness,cv.LINE_AA)
cv.putText(img,'OpenCV',(10,500), font, 4,(255,255,255),2,cv.LINE_AA)
# 3 图像展示
plt.imshow(img[:,:,::-1])
plt.title('匹配结果'), plt.xticks([]), plt.yticks([])
plt.show()

In [15]:
import cv2
# 读一个图片并进行显示(图片路径需自己指定)
path='image1.jpg'
img=cv2.imread(path)
cv2.imshow("image",img)
cv2.waitKey(0)

-1

In [6]:
import numpy as np
import cv2 as cv
path='image1.jpg'
img=cv2.imread(path)
# 获取某个像素点的值
px = img[100,100]
print(px)
# 仅获取蓝色通道的强度值
blue = img[100,100,0]
print(blue)
# 修改某个位置的像素值
img[100,100] = [255,255,255]
px = img[100,100]
print(px)

[213 181 128]
213
[255 255 255]


In [9]:
# 通道拆分
print('img.shape:',img.shape)
b,g,r = cv.split(img)
print(b.shape)
print('b:\n',b)
print(g.shape)
print('g:\n',g)
print(r.shape)
print('r:\n',r)
# 通道合并
img = cv.merge((b,g,r))
print('img.shape:',img.shape)

img.shape: (300, 300, 3)
(300, 300)
b:
 [[ 25  17  33 ...  80  75  65]
 [ 25  32  42 ...  75  75  79]
 [ 37  36  24 ...  56  35  42]
 ...
 [146 156 150 ...  87  90  90]
 [153 160 154 ...  88  91  91]
 [157 164 153 ...  89  91  92]]
(300, 300)
g:
 [[ 82  72  84 ... 112 110 100]
 [ 82  87  93 ... 109 110 116]
 [ 96  93  77 ...  93  72  82]
 ...
 [149 159 150 ...  93  96  96]
 [156 163 152 ...  96  99  99]
 [160 164 152 ...  97  99 100]]
(300, 300)
r:
 [[ 91  81  94 ... 111 106  96]
 [ 91  96 103 ... 108 106 112]
 [105 102  87 ...  89  68  77]
 ...
 [127 134 126 ...  98 101 101]
 [131 138 128 ... 103 106 106]
 [135 140 126 ... 104 106 107]]
img.shape: (300, 300, 3)


In [16]:
img_crop=img[100:150,100:150]
cv2.namedWindow('image', cv2.WINDOW_NORMAL)
# 改变窗口位置：left top
 
cv2.moveWindow("image", 200, 200)

cv2.imshow('image',img_crop)
cv2.waitKey(0)

-1